# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct RatingsApi <: SwaggerApi
    client::Swagger.Client
end

"""
Historical SP+ ratings by conference
Get average SP+ historical rating data by conference
Param: year::Int32
Param: conference::String
Return: Vector{ConferenceSPRating}
"""
function getConferenceSPRatings(_api::RatingsApi; year=nothing, conference=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getConferenceSPRatings", :minimum, year, 1970, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{ConferenceSPRating}, "/ratings/sp/conferences", [])
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "conference", conference)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

"""
Historical SP+ ratings
SP+ rating data
Param: year::Int32
Param: team::String
Return: Vector{TeamSPRating}
"""
function getSPRatings(_api::RatingsApi; year=nothing, team=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getSPRatings", :minimum, year, 1970, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{TeamSPRating}, "/ratings/sp", [])
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

"""
Historical SRS ratings
SRS rating data (requires either a year or team specified)
Param: year::Int32
Param: team::String
Param: conference::String
Return: Vector{TeamSRSRating}
"""
function getSRSRatings(_api::RatingsApi; year=nothing, team=nothing, conference=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getSRSRatings", :minimum, year, 1897, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{TeamSRSRating}, "/ratings/srs", [])
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_param(_ctx.query, "conference", conference)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

export getConferenceSPRatings, getSPRatings, getSRSRatings
