# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct CoachesApi <: SwaggerApi
    client::Swagger.Client
end

"""
Coaching records and history
Coaching history
Param: firstName::String
Param: lastName::String
Param: team::String
Param: year::Int32
Param: minYear::Int32
Param: maxYear::Int32
Return: Vector{Any}
"""
function getCoaches(_api::CoachesApi; firstName=nothing, lastName=nothing, team=nothing, year=nothing, minYear=nothing, maxYear=nothing, _mediaType=nothing)
    Swagger.validate_param("minYear", "getCoaches", :minimum, minYear, 1869, false)

    Swagger.validate_param("maxYear", "getCoaches", :minimum, maxYear, 1869, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{Any}, "/coaches", [])
    Swagger.set_param(_ctx.query, "firstName", firstName)  # type String
    Swagger.set_param(_ctx.query, "lastName", lastName)  # type String
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "minYear", minYear)  # type Int32
    Swagger.set_param(_ctx.query, "maxYear", maxYear)  # type Int32
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

export getCoaches
