# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct StatsApi <: SwaggerApi
    client::Swagger.Client
end

"""
Advanced team metrics by game
Advanced team game stats
Param: year::Int32
Param: week::Int32
Param: team::String
Param: opponent::String
Param: excludeGarbageTime::Bool
Param: seasonType::String
Return: Vector{AdvancedGameStat}
"""
function getAdvancedTeamGameStats(_api::StatsApi; year=nothing, week=nothing, team=nothing, opponent=nothing, excludeGarbageTime=nothing, seasonType=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getAdvancedTeamGameStats", :minimum, year, 2001, false)

    Swagger.validate_param("week", "getAdvancedTeamGameStats", :maximum, week, 16, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{AdvancedGameStat}, "/stats/game/advanced", [])
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "week", week)  # type Int32
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_param(_ctx.query, "opponent", opponent)  # type String
    Swagger.set_param(_ctx.query, "excludeGarbageTime", excludeGarbageTime)  # type Bool
    Swagger.set_param(_ctx.query, "seasonType", seasonType)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

"""
Advanced team metrics by season
Advanced team season stats
Param: year::Int32
Param: team::String
Param: excludeGarbageTime::Bool
Param: startWeek::Int32
Param: endWeek::Int32
Return: Vector{AdvancedSeasonStat}
"""
function getAdvancedTeamSeasonStats(_api::StatsApi; year=nothing, team=nothing, excludeGarbageTime=nothing, startWeek=nothing, endWeek=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getAdvancedTeamSeasonStats", :minimum, year, 2001, false)

    Swagger.validate_param("startWeek", "getAdvancedTeamSeasonStats", :maximum, startWeek, 16, false)

    Swagger.validate_param("endWeek", "getAdvancedTeamSeasonStats", :maximum, endWeek, 16, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{AdvancedSeasonStat}, "/stats/season/advanced", [])
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_param(_ctx.query, "excludeGarbageTime", excludeGarbageTime)  # type Bool
    Swagger.set_param(_ctx.query, "startWeek", startWeek)  # type Int32
    Swagger.set_param(_ctx.query, "endWeek", endWeek)  # type Int32
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

"""
Team stat categories
Stat category list
Return: Vector{String}
"""
function getStatCategories(_api::StatsApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Vector{String}, "/stats/categories", [])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

"""
Team statistics by season
Team season stats
Param: year::Int32
Param: team::String
Param: conference::String
Param: startWeek::Int32
Param: endWeek::Int32
Return: Vector{TeamSeasonStat}
"""
function getTeamSeasonStats(_api::StatsApi; year=nothing, team=nothing, conference=nothing, startWeek=nothing, endWeek=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getTeamSeasonStats", :minimum, year, 2001, false)

    Swagger.validate_param("startWeek", "getTeamSeasonStats", :maximum, startWeek, 16, false)

    Swagger.validate_param("endWeek", "getTeamSeasonStats", :maximum, endWeek, 16, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{TeamSeasonStat}, "/stats/season", [])
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_param(_ctx.query, "conference", conference)  # type String
    Swagger.set_param(_ctx.query, "startWeek", startWeek)  # type Int32
    Swagger.set_param(_ctx.query, "endWeek", endWeek)  # type Int32
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

export getAdvancedTeamGameStats, getAdvancedTeamSeasonStats, getStatCategories, getTeamSeasonStats
