# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct VenuesApi <: SwaggerApi
    client::Swagger.Client
end

"""
Arena and venue information
Venues
Return: Vector{Venue}
"""
function getVenues(_api::VenuesApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Vector{Venue}, "/venues", [])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

export getVenues
