# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct DrivesApi <: SwaggerApi
    client::Swagger.Client
end

"""
Drive data and results
Get game drives
Param: year::Int32 (required)
Param: seasonType::String
Param: week::Int32
Param: team::String
Param: offense::String
Param: defense::String
Param: conference::String
Param: offenseConference::String
Param: defenseConference::String
Return: Vector{Drive}
"""
function getDrvies(_api::DrivesApi, year::Int32; seasonType=nothing, week=nothing, team=nothing, offense=nothing, defense=nothing, conference=nothing, offenseConference=nothing, defenseConference=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getDrvies", :minimum, year, 2001, false)

    Swagger.validate_param("week", "getDrvies", :maximum, week, 16, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{Drive}, "/drives", [])
    Swagger.set_param(_ctx.query, "seasonType", seasonType)  # type String
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "week", week)  # type Int32
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_param(_ctx.query, "offense", offense)  # type String
    Swagger.set_param(_ctx.query, "defense", defense)  # type String
    Swagger.set_param(_ctx.query, "conference", conference)  # type String
    Swagger.set_param(_ctx.query, "offenseConference", offenseConference)  # type String
    Swagger.set_param(_ctx.query, "defenseConference", defenseConference)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

export getDrvies
