# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct RankingsApi <: SwaggerApi
    client::Swagger.Client
end

"""
Historical polls and rankings
Poll rankings
Param: year::Int32 (required)
Param: week::Int32
Param: seasonType::String
Return: Vector{RankingWeek}
"""
function getRankings(_api::RankingsApi, year::Int32; week=nothing, seasonType=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getRankings", :minimum, year, 1936, false)

    Swagger.validate_param("week", "getRankings", :maximum, week, 16, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{RankingWeek}, "/rankings", [])
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "week", week)  # type Int32
    Swagger.set_param(_ctx.query, "seasonType", seasonType)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

export getRankings
