# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct BettingApi <: SwaggerApi
    client::Swagger.Client
end

"""
Betting lines
Closing betting lines
Param: gameId::Int32
Param: year::Int32
Param: week::Int32
Param: seasonType::String
Param: team::String
Param: home::String
Param: away::String
Param: conference::String
Return: Vector{GameLines}
"""
function getLines(_api::BettingApi; gameId=nothing, year=nothing, week=nothing, seasonType=nothing, team=nothing, home=nothing, away=nothing, conference=nothing, _mediaType=nothing)
    Swagger.validate_param("year", "getLines", :minimum, year, 2013, false)

    Swagger.validate_param("week", "getLines", :maximum, week, 16, false)

    _ctx = Swagger.Ctx(_api.client, "GET", Vector{GameLines}, "/lines", [])
    Swagger.set_param(_ctx.query, "gameId", gameId)  # type Int32
    Swagger.set_param(_ctx.query, "year", year)  # type Int32
    Swagger.set_param(_ctx.query, "week", week)  # type Int32
    Swagger.set_param(_ctx.query, "seasonType", seasonType)  # type String
    Swagger.set_param(_ctx.query, "team", team)  # type String
    Swagger.set_param(_ctx.query, "home", home)  # type String
    Swagger.set_param(_ctx.query, "away", away)  # type String
    Swagger.set_param(_ctx.query, "conference", conference)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    Swagger.exec(_ctx)
end

export getLines
