# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module CollegeFootballData

using Random
using Dates
using HTTP
using Swagger
import Swagger: field_name, property_type, hasproperty, validate_property, SwaggerApi, SwaggerModel
import Base: convert, propertynames

include("modelincludes.jl")

include("api_BettingApi.jl")
include("api_CoachesApi.jl")
include("api_ConferencesApi.jl")
include("api_DrivesApi.jl")
include("api_GamesApi.jl")
include("api_MetricsApi.jl")
include("api_PlayersApi.jl")
include("api_PlaysApi.jl")
include("api_RankingsApi.jl")
include("api_RatingsApi.jl")
include("api_RecruitingApi.jl")
include("api_StatsApi.jl")
include("api_TeamsApi.jl")
include("api_VenuesApi.jl")

# export models
export convert, AdvancedGameStat
export convert, AdvancedGameStatOffense
export convert, AdvancedGameStatOffenseRushingPlays
export convert, AdvancedGameStatOffenseStandardDowns
export convert, AdvancedSeasonStat
export convert, AdvancedSeasonStatDefense
export convert, AdvancedSeasonStatOffense
export convert, AdvancedSeasonStatOffenseFieldPosition
export convert, AdvancedSeasonStatOffenseRushingPlays
export convert, AdvancedSeasonStatOffenseStandardDowns
export convert, BoxScore
export convert, BoxScorePlayers
export convert, BoxScorePlayersAverage
export convert, BoxScorePlayersPpa
export convert, BoxScorePlayersUsage
export convert, BoxScoreTeams
export convert, BoxScoreTeamsExplosiveness
export convert, BoxScoreTeamsFieldPosition
export convert, BoxScoreTeamsHavoc
export convert, BoxScoreTeamsOverall
export convert, BoxScoreTeamsPpa
export convert, BoxScoreTeamsRushing
export convert, BoxScoreTeamsScoringOpportunities
export convert, BoxScoreTeamsSuccessRates
export convert, Conference
export convert, ConferenceSPRating
export convert, Drive
export convert, DriveStartTime
export convert, Game
export convert, GameLines
export convert, GameLinesLines
export convert, GameMedia
export convert, GamePPA
export convert, GamePPAOffense
export convert, InlineResponse200
export convert, Play
export convert, PlayStat
export convert, PlayStatType
export convert, PlayType
export convert, PlayWP
export convert, Player
export convert, PlayerGame
export convert, PlayerGameAthletes
export convert, PlayerGameCategories
export convert, PlayerGamePPA
export convert, PlayerGamePPAAveragePPA
export convert, PlayerGameSchool
export convert, PlayerGameTeams
export convert, PlayerGameTypes
export convert, PlayerSearchResult
export convert, PlayerSeasonPPA
export convert, PlayerSeasonPPAAveragePPA
export convert, PlayerSeasonStat
export convert, PlayerUsage
export convert, PlayerUsageUsage
export convert, PositionGroupRecruitingRating
export convert, PredictedPoints
export convert, PregameWP
export convert, RankingWeek
export convert, RankingWeekPolls
export convert, RankingWeekRanks
export convert, Recruit
export convert, ReturningProduction
export convert, Team
export convert, TeamGame
export convert, TeamGameStats
export convert, TeamGameTeams
export convert, TeamMatchup
export convert, TeamMatchupGames
export convert, TeamPPA
export convert, TeamPPAOffense
export convert, TeamPPAOffenseCumulative
export convert, TeamRecord
export convert, TeamRecordTotal
export convert, TeamRecruitingRank
export convert, TeamSPRating
export convert, TeamSPRatingDefense
export convert, TeamSPRatingDefenseHavoc
export convert, TeamSPRatingOffense
export convert, TeamSPRatingSpecialTeams
export convert, TeamSRSRating
export convert, TeamSeason
export convert, TeamSeasonStat
export convert, TeamTalent
export convert, Venue
export convert, VenueLocation

# export operations
export convert, BettingApi, CoachesApi, ConferencesApi, DrivesApi, GamesApi, MetricsApi, PlayersApi, PlaysApi, RankingsApi, RatingsApi, RecruitingApi, StatsApi, TeamsApi, VenuesApi

export check_required, field_name, property_type, hasproperty, propertynames, validate_property, convert

end
