# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module CollegeFootballData

using JSON3, HTTP

include("scripts/swagger.jl")
include("api/API.jl")

end
