# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct BoxScoreTeamsHavoc <: SwaggerModel
    team::Any # spec type: Union{ Nothing, String } # spec name: team
    total::Any # spec type: Union{ Nothing, Float32 } # spec name: total
    frontSeven::Any # spec type: Union{ Nothing, Float32 } # spec name: frontSeven
    db::Any # spec type: Union{ Nothing, Float32 } # spec name: db

    function BoxScoreTeamsHavoc(;team=nothing, total=nothing, frontSeven=nothing, db=nothing)
        o = new()
        validate_property(BoxScoreTeamsHavoc, Symbol("team"), team)
        setfield!(o, Symbol("team"), team)
        validate_property(BoxScoreTeamsHavoc, Symbol("total"), total)
        setfield!(o, Symbol("total"), total)
        validate_property(BoxScoreTeamsHavoc, Symbol("frontSeven"), frontSeven)
        setfield!(o, Symbol("frontSeven"), frontSeven)
        validate_property(BoxScoreTeamsHavoc, Symbol("db"), db)
        setfield!(o, Symbol("db"), db)
        o
    end
end # type BoxScoreTeamsHavoc

const _property_map_BoxScoreTeamsHavoc = Dict{Symbol,Symbol}(Symbol("team")=>Symbol("team"), Symbol("total")=>Symbol("total"), Symbol("frontSeven")=>Symbol("frontSeven"), Symbol("db")=>Symbol("db"))
const _property_types_BoxScoreTeamsHavoc = Dict{Symbol,String}(Symbol("team")=>"String", Symbol("total")=>"Float32", Symbol("frontSeven")=>"Float32", Symbol("db")=>"Float32")
Base.propertynames(::Type{ BoxScoreTeamsHavoc }) = collect(keys(_property_map_BoxScoreTeamsHavoc))
Swagger.property_type(::Type{ BoxScoreTeamsHavoc }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BoxScoreTeamsHavoc[name]))}
Swagger.field_name(::Type{ BoxScoreTeamsHavoc }, property_name::Symbol) =  _property_map_BoxScoreTeamsHavoc[property_name]

function check_required(o::BoxScoreTeamsHavoc)
    true
end

function validate_property(::Type{ BoxScoreTeamsHavoc }, name::Symbol, val)
end
