# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct BoxScoreTeamsSuccessRates <: SwaggerModel
    team::Any # spec type: Union{ Nothing, String } # spec name: team
    overall::Any # spec type: Union{ Nothing, BoxScoreTeamsOverall } # spec name: overall
    standardDowns::Any # spec type: Union{ Nothing, BoxScoreTeamsOverall } # spec name: standardDowns
    passingDowns::Any # spec type: Union{ Nothing, BoxScoreTeamsOverall } # spec name: passingDowns

    function BoxScoreTeamsSuccessRates(;team=nothing, overall=nothing, standardDowns=nothing, passingDowns=nothing)
        o = new()
        validate_property(BoxScoreTeamsSuccessRates, Symbol("team"), team)
        setfield!(o, Symbol("team"), team)
        validate_property(BoxScoreTeamsSuccessRates, Symbol("overall"), overall)
        setfield!(o, Symbol("overall"), overall)
        validate_property(BoxScoreTeamsSuccessRates, Symbol("standardDowns"), standardDowns)
        setfield!(o, Symbol("standardDowns"), standardDowns)
        validate_property(BoxScoreTeamsSuccessRates, Symbol("passingDowns"), passingDowns)
        setfield!(o, Symbol("passingDowns"), passingDowns)
        o
    end
end # type BoxScoreTeamsSuccessRates

const _property_map_BoxScoreTeamsSuccessRates = Dict{Symbol,Symbol}(Symbol("team")=>Symbol("team"), Symbol("overall")=>Symbol("overall"), Symbol("standardDowns")=>Symbol("standardDowns"), Symbol("passingDowns")=>Symbol("passingDowns"))
const _property_types_BoxScoreTeamsSuccessRates = Dict{Symbol,String}(Symbol("team")=>"String", Symbol("overall")=>"BoxScoreTeamsOverall", Symbol("standardDowns")=>"BoxScoreTeamsOverall", Symbol("passingDowns")=>"BoxScoreTeamsOverall")
Base.propertynames(::Type{ BoxScoreTeamsSuccessRates }) = collect(keys(_property_map_BoxScoreTeamsSuccessRates))
Swagger.property_type(::Type{ BoxScoreTeamsSuccessRates }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BoxScoreTeamsSuccessRates[name]))}
Swagger.field_name(::Type{ BoxScoreTeamsSuccessRates }, property_name::Symbol) =  _property_map_BoxScoreTeamsSuccessRates[property_name]

function check_required(o::BoxScoreTeamsSuccessRates)
    true
end

function validate_property(::Type{ BoxScoreTeamsSuccessRates }, name::Symbol, val)
end
