# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AdvancedSeasonStatDefense <: SwaggerModel
    plays::Any # spec type: Union{ Nothing, Int32 } # spec name: plays
    drives::Any # spec type: Union{ Nothing, Int32 } # spec name: drives
    ppa::Any # spec type: Union{ Nothing, Float32 } # spec name: ppa
    totalPPA::Any # spec type: Union{ Nothing, Float32 } # spec name: totalPPA
    successRate::Any # spec type: Union{ Nothing, Float32 } # spec name: successRate
    explosiveness::Any # spec type: Union{ Nothing, Float32 } # spec name: explosiveness
    powerSuccess::Any # spec type: Union{ Nothing, Float32 } # spec name: powerSuccess
    stuffRate::Any # spec type: Union{ Nothing, Float32 } # spec name: stuffRate
    lineYards::Any # spec type: Union{ Nothing, Float32 } # spec name: lineYards
    lineYardsTotal::Any # spec type: Union{ Nothing, Float32 } # spec name: lineYardsTotal
    secondLevelYards::Any # spec type: Union{ Nothing, Float32 } # spec name: secondLevelYards
    secondLevelYardsTotal::Any # spec type: Union{ Nothing, Int32 } # spec name: secondLevelYardsTotal
    openFieldYards::Any # spec type: Union{ Nothing, Float32 } # spec name: openFieldYards
    openFieldYardsTotal::Any # spec type: Union{ Nothing, Int32 } # spec name: openFieldYardsTotal
    pointsPerOpportunity::Any # spec type: Union{ Nothing, Float32 } # spec name: pointsPerOpportunity
    fieldPosition::Any # spec type: Union{ Nothing, AdvancedSeasonStatOffenseFieldPosition } # spec name: fieldPosition
    havoc::Any # spec type: Union{ Nothing, TeamSPRatingDefenseHavoc } # spec name: havoc
    standardDowns::Any # spec type: Union{ Nothing, AdvancedSeasonStatOffenseStandardDowns } # spec name: standardDowns
    passingDowns::Any # spec type: Union{ Nothing, AdvancedSeasonStatOffenseStandardDowns } # spec name: passingDowns
    rushingPlays::Any # spec type: Union{ Nothing, AdvancedSeasonStatOffenseRushingPlays } # spec name: rushingPlays
    passingPlays::Any # spec type: Union{ Nothing, AdvancedSeasonStatOffenseRushingPlays } # spec name: passingPlays

    function AdvancedSeasonStatDefense(;plays=nothing, drives=nothing, ppa=nothing, totalPPA=nothing, successRate=nothing, explosiveness=nothing, powerSuccess=nothing, stuffRate=nothing, lineYards=nothing, lineYardsTotal=nothing, secondLevelYards=nothing, secondLevelYardsTotal=nothing, openFieldYards=nothing, openFieldYardsTotal=nothing, pointsPerOpportunity=nothing, fieldPosition=nothing, havoc=nothing, standardDowns=nothing, passingDowns=nothing, rushingPlays=nothing, passingPlays=nothing)
        o = new()
        validate_property(AdvancedSeasonStatDefense, Symbol("plays"), plays)
        setfield!(o, Symbol("plays"), plays)
        validate_property(AdvancedSeasonStatDefense, Symbol("drives"), drives)
        setfield!(o, Symbol("drives"), drives)
        validate_property(AdvancedSeasonStatDefense, Symbol("ppa"), ppa)
        setfield!(o, Symbol("ppa"), ppa)
        validate_property(AdvancedSeasonStatDefense, Symbol("totalPPA"), totalPPA)
        setfield!(o, Symbol("totalPPA"), totalPPA)
        validate_property(AdvancedSeasonStatDefense, Symbol("successRate"), successRate)
        setfield!(o, Symbol("successRate"), successRate)
        validate_property(AdvancedSeasonStatDefense, Symbol("explosiveness"), explosiveness)
        setfield!(o, Symbol("explosiveness"), explosiveness)
        validate_property(AdvancedSeasonStatDefense, Symbol("powerSuccess"), powerSuccess)
        setfield!(o, Symbol("powerSuccess"), powerSuccess)
        validate_property(AdvancedSeasonStatDefense, Symbol("stuffRate"), stuffRate)
        setfield!(o, Symbol("stuffRate"), stuffRate)
        validate_property(AdvancedSeasonStatDefense, Symbol("lineYards"), lineYards)
        setfield!(o, Symbol("lineYards"), lineYards)
        validate_property(AdvancedSeasonStatDefense, Symbol("lineYardsTotal"), lineYardsTotal)
        setfield!(o, Symbol("lineYardsTotal"), lineYardsTotal)
        validate_property(AdvancedSeasonStatDefense, Symbol("secondLevelYards"), secondLevelYards)
        setfield!(o, Symbol("secondLevelYards"), secondLevelYards)
        validate_property(AdvancedSeasonStatDefense, Symbol("secondLevelYardsTotal"), secondLevelYardsTotal)
        setfield!(o, Symbol("secondLevelYardsTotal"), secondLevelYardsTotal)
        validate_property(AdvancedSeasonStatDefense, Symbol("openFieldYards"), openFieldYards)
        setfield!(o, Symbol("openFieldYards"), openFieldYards)
        validate_property(AdvancedSeasonStatDefense, Symbol("openFieldYardsTotal"), openFieldYardsTotal)
        setfield!(o, Symbol("openFieldYardsTotal"), openFieldYardsTotal)
        validate_property(AdvancedSeasonStatDefense, Symbol("pointsPerOpportunity"), pointsPerOpportunity)
        setfield!(o, Symbol("pointsPerOpportunity"), pointsPerOpportunity)
        validate_property(AdvancedSeasonStatDefense, Symbol("fieldPosition"), fieldPosition)
        setfield!(o, Symbol("fieldPosition"), fieldPosition)
        validate_property(AdvancedSeasonStatDefense, Symbol("havoc"), havoc)
        setfield!(o, Symbol("havoc"), havoc)
        validate_property(AdvancedSeasonStatDefense, Symbol("standardDowns"), standardDowns)
        setfield!(o, Symbol("standardDowns"), standardDowns)
        validate_property(AdvancedSeasonStatDefense, Symbol("passingDowns"), passingDowns)
        setfield!(o, Symbol("passingDowns"), passingDowns)
        validate_property(AdvancedSeasonStatDefense, Symbol("rushingPlays"), rushingPlays)
        setfield!(o, Symbol("rushingPlays"), rushingPlays)
        validate_property(AdvancedSeasonStatDefense, Symbol("passingPlays"), passingPlays)
        setfield!(o, Symbol("passingPlays"), passingPlays)
        o
    end
end # type AdvancedSeasonStatDefense

const _property_map_AdvancedSeasonStatDefense = Dict{Symbol,Symbol}(Symbol("plays")=>Symbol("plays"), Symbol("drives")=>Symbol("drives"), Symbol("ppa")=>Symbol("ppa"), Symbol("totalPPA")=>Symbol("totalPPA"), Symbol("successRate")=>Symbol("successRate"), Symbol("explosiveness")=>Symbol("explosiveness"), Symbol("powerSuccess")=>Symbol("powerSuccess"), Symbol("stuffRate")=>Symbol("stuffRate"), Symbol("lineYards")=>Symbol("lineYards"), Symbol("lineYardsTotal")=>Symbol("lineYardsTotal"), Symbol("secondLevelYards")=>Symbol("secondLevelYards"), Symbol("secondLevelYardsTotal")=>Symbol("secondLevelYardsTotal"), Symbol("openFieldYards")=>Symbol("openFieldYards"), Symbol("openFieldYardsTotal")=>Symbol("openFieldYardsTotal"), Symbol("pointsPerOpportunity")=>Symbol("pointsPerOpportunity"), Symbol("fieldPosition")=>Symbol("fieldPosition"), Symbol("havoc")=>Symbol("havoc"), Symbol("standardDowns")=>Symbol("standardDowns"), Symbol("passingDowns")=>Symbol("passingDowns"), Symbol("rushingPlays")=>Symbol("rushingPlays"), Symbol("passingPlays")=>Symbol("passingPlays"))
const _property_types_AdvancedSeasonStatDefense = Dict{Symbol,String}(Symbol("plays")=>"Int32", Symbol("drives")=>"Int32", Symbol("ppa")=>"Float32", Symbol("totalPPA")=>"Float32", Symbol("successRate")=>"Float32", Symbol("explosiveness")=>"Float32", Symbol("powerSuccess")=>"Float32", Symbol("stuffRate")=>"Float32", Symbol("lineYards")=>"Float32", Symbol("lineYardsTotal")=>"Float32", Symbol("secondLevelYards")=>"Float32", Symbol("secondLevelYardsTotal")=>"Int32", Symbol("openFieldYards")=>"Float32", Symbol("openFieldYardsTotal")=>"Int32", Symbol("pointsPerOpportunity")=>"Float32", Symbol("fieldPosition")=>"AdvancedSeasonStatOffenseFieldPosition", Symbol("havoc")=>"TeamSPRatingDefenseHavoc", Symbol("standardDowns")=>"AdvancedSeasonStatOffenseStandardDowns", Symbol("passingDowns")=>"AdvancedSeasonStatOffenseStandardDowns", Symbol("rushingPlays")=>"AdvancedSeasonStatOffenseRushingPlays", Symbol("passingPlays")=>"AdvancedSeasonStatOffenseRushingPlays")
Base.propertynames(::Type{ AdvancedSeasonStatDefense }) = collect(keys(_property_map_AdvancedSeasonStatDefense))
Swagger.property_type(::Type{ AdvancedSeasonStatDefense }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdvancedSeasonStatDefense[name]))}
Swagger.field_name(::Type{ AdvancedSeasonStatDefense }, property_name::Symbol) =  _property_map_AdvancedSeasonStatDefense[property_name]

function check_required(o::AdvancedSeasonStatDefense)
    true
end

function validate_property(::Type{ AdvancedSeasonStatDefense }, name::Symbol, val)
end
