# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct RankingWeekRanks <: SwaggerModel
    rank::Any # spec type: Union{ Nothing, Int32 } # spec name: rank
    school::Any # spec type: Union{ Nothing, String } # spec name: school
    conference::Any # spec type: Union{ Nothing, String } # spec name: conference
    firstPlaceVotes::Any # spec type: Union{ Nothing, Int32 } # spec name: firstPlaceVotes
    points::Any # spec type: Union{ Nothing, Int32 } # spec name: points

    function RankingWeekRanks(;rank=nothing, school=nothing, conference=nothing, firstPlaceVotes=nothing, points=nothing)
        o = new()
        validate_property(RankingWeekRanks, Symbol("rank"), rank)
        setfield!(o, Symbol("rank"), rank)
        validate_property(RankingWeekRanks, Symbol("school"), school)
        setfield!(o, Symbol("school"), school)
        validate_property(RankingWeekRanks, Symbol("conference"), conference)
        setfield!(o, Symbol("conference"), conference)
        validate_property(RankingWeekRanks, Symbol("firstPlaceVotes"), firstPlaceVotes)
        setfield!(o, Symbol("firstPlaceVotes"), firstPlaceVotes)
        validate_property(RankingWeekRanks, Symbol("points"), points)
        setfield!(o, Symbol("points"), points)
        o
    end
end # type RankingWeekRanks

const _property_map_RankingWeekRanks = Dict{Symbol,Symbol}(Symbol("rank")=>Symbol("rank"), Symbol("school")=>Symbol("school"), Symbol("conference")=>Symbol("conference"), Symbol("firstPlaceVotes")=>Symbol("firstPlaceVotes"), Symbol("points")=>Symbol("points"))
const _property_types_RankingWeekRanks = Dict{Symbol,String}(Symbol("rank")=>"Int32", Symbol("school")=>"String", Symbol("conference")=>"String", Symbol("firstPlaceVotes")=>"Int32", Symbol("points")=>"Int32")
Base.propertynames(::Type{ RankingWeekRanks }) = collect(keys(_property_map_RankingWeekRanks))
Swagger.property_type(::Type{ RankingWeekRanks }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RankingWeekRanks[name]))}
Swagger.field_name(::Type{ RankingWeekRanks }, property_name::Symbol) =  _property_map_RankingWeekRanks[property_name]

function check_required(o::RankingWeekRanks)
    true
end

function validate_property(::Type{ RankingWeekRanks }, name::Symbol, val)
end
