# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct BoxScorePlayersAverage <: SwaggerModel
    total::Any # spec type: Union{ Nothing, Float32 } # spec name: total
    quarter1::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter1
    quarter2::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter2
    quarter3::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter3
    quarter4::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter4
    rushing::Any # spec type: Union{ Nothing, Float32 } # spec name: rushing
    passing::Any # spec type: Union{ Nothing, Float32 } # spec name: passing

    function BoxScorePlayersAverage(;total=nothing, quarter1=nothing, quarter2=nothing, quarter3=nothing, quarter4=nothing, rushing=nothing, passing=nothing)
        o = new()
        validate_property(BoxScorePlayersAverage, Symbol("total"), total)
        setfield!(o, Symbol("total"), total)
        validate_property(BoxScorePlayersAverage, Symbol("quarter1"), quarter1)
        setfield!(o, Symbol("quarter1"), quarter1)
        validate_property(BoxScorePlayersAverage, Symbol("quarter2"), quarter2)
        setfield!(o, Symbol("quarter2"), quarter2)
        validate_property(BoxScorePlayersAverage, Symbol("quarter3"), quarter3)
        setfield!(o, Symbol("quarter3"), quarter3)
        validate_property(BoxScorePlayersAverage, Symbol("quarter4"), quarter4)
        setfield!(o, Symbol("quarter4"), quarter4)
        validate_property(BoxScorePlayersAverage, Symbol("rushing"), rushing)
        setfield!(o, Symbol("rushing"), rushing)
        validate_property(BoxScorePlayersAverage, Symbol("passing"), passing)
        setfield!(o, Symbol("passing"), passing)
        o
    end
end # type BoxScorePlayersAverage

const _property_map_BoxScorePlayersAverage = Dict{Symbol,Symbol}(Symbol("total")=>Symbol("total"), Symbol("quarter1")=>Symbol("quarter1"), Symbol("quarter2")=>Symbol("quarter2"), Symbol("quarter3")=>Symbol("quarter3"), Symbol("quarter4")=>Symbol("quarter4"), Symbol("rushing")=>Symbol("rushing"), Symbol("passing")=>Symbol("passing"))
const _property_types_BoxScorePlayersAverage = Dict{Symbol,String}(Symbol("total")=>"Float32", Symbol("quarter1")=>"Float32", Symbol("quarter2")=>"Float32", Symbol("quarter3")=>"Float32", Symbol("quarter4")=>"Float32", Symbol("rushing")=>"Float32", Symbol("passing")=>"Float32")
Base.propertynames(::Type{ BoxScorePlayersAverage }) = collect(keys(_property_map_BoxScorePlayersAverage))
Swagger.property_type(::Type{ BoxScorePlayersAverage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BoxScorePlayersAverage[name]))}
Swagger.field_name(::Type{ BoxScorePlayersAverage }, property_name::Symbol) =  _property_map_BoxScorePlayersAverage[property_name]

function check_required(o::BoxScorePlayersAverage)
    true
end

function validate_property(::Type{ BoxScorePlayersAverage }, name::Symbol, val)
end
