# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct TeamSPRatingDefenseHavoc <: SwaggerModel
    total::Any # spec type: Union{ Nothing, Float32 } # spec name: total
    frontSeven::Any # spec type: Union{ Nothing, Float32 } # spec name: frontSeven
    db::Any # spec type: Union{ Nothing, Float32 } # spec name: db

    function TeamSPRatingDefenseHavoc(;total=nothing, frontSeven=nothing, db=nothing)
        o = new()
        validate_property(TeamSPRatingDefenseHavoc, Symbol("total"), total)
        setfield!(o, Symbol("total"), total)
        validate_property(TeamSPRatingDefenseHavoc, Symbol("frontSeven"), frontSeven)
        setfield!(o, Symbol("frontSeven"), frontSeven)
        validate_property(TeamSPRatingDefenseHavoc, Symbol("db"), db)
        setfield!(o, Symbol("db"), db)
        o
    end
end # type TeamSPRatingDefenseHavoc

const _property_map_TeamSPRatingDefenseHavoc = Dict{Symbol,Symbol}(Symbol("total")=>Symbol("total"), Symbol("frontSeven")=>Symbol("frontSeven"), Symbol("db")=>Symbol("db"))
const _property_types_TeamSPRatingDefenseHavoc = Dict{Symbol,String}(Symbol("total")=>"Float32", Symbol("frontSeven")=>"Float32", Symbol("db")=>"Float32")
Base.propertynames(::Type{ TeamSPRatingDefenseHavoc }) = collect(keys(_property_map_TeamSPRatingDefenseHavoc))
Swagger.property_type(::Type{ TeamSPRatingDefenseHavoc }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TeamSPRatingDefenseHavoc[name]))}
Swagger.field_name(::Type{ TeamSPRatingDefenseHavoc }, property_name::Symbol) =  _property_map_TeamSPRatingDefenseHavoc[property_name]

function check_required(o::TeamSPRatingDefenseHavoc)
    true
end

function validate_property(::Type{ TeamSPRatingDefenseHavoc }, name::Symbol, val)
end
