# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct GamePPAOffense <: SwaggerModel
    overall::Any # spec type: Union{ Nothing, Float32 } # spec name: overall
    passing::Any # spec type: Union{ Nothing, Float32 } # spec name: passing
    rushing::Any # spec type: Union{ Nothing, Float32 } # spec name: rushing
    firstDown::Any # spec type: Union{ Nothing, Float32 } # spec name: firstDown
    secondDown::Any # spec type: Union{ Nothing, Float32 } # spec name: secondDown
    thirdDown::Any # spec type: Union{ Nothing, Float32 } # spec name: thirdDown

    function GamePPAOffense(;overall=nothing, passing=nothing, rushing=nothing, firstDown=nothing, secondDown=nothing, thirdDown=nothing)
        o = new()
        validate_property(GamePPAOffense, Symbol("overall"), overall)
        setfield!(o, Symbol("overall"), overall)
        validate_property(GamePPAOffense, Symbol("passing"), passing)
        setfield!(o, Symbol("passing"), passing)
        validate_property(GamePPAOffense, Symbol("rushing"), rushing)
        setfield!(o, Symbol("rushing"), rushing)
        validate_property(GamePPAOffense, Symbol("firstDown"), firstDown)
        setfield!(o, Symbol("firstDown"), firstDown)
        validate_property(GamePPAOffense, Symbol("secondDown"), secondDown)
        setfield!(o, Symbol("secondDown"), secondDown)
        validate_property(GamePPAOffense, Symbol("thirdDown"), thirdDown)
        setfield!(o, Symbol("thirdDown"), thirdDown)
        o
    end
end # type GamePPAOffense

const _property_map_GamePPAOffense = Dict{Symbol,Symbol}(Symbol("overall")=>Symbol("overall"), Symbol("passing")=>Symbol("passing"), Symbol("rushing")=>Symbol("rushing"), Symbol("firstDown")=>Symbol("firstDown"), Symbol("secondDown")=>Symbol("secondDown"), Symbol("thirdDown")=>Symbol("thirdDown"))
const _property_types_GamePPAOffense = Dict{Symbol,String}(Symbol("overall")=>"Float32", Symbol("passing")=>"Float32", Symbol("rushing")=>"Float32", Symbol("firstDown")=>"Float32", Symbol("secondDown")=>"Float32", Symbol("thirdDown")=>"Float32")
Base.propertynames(::Type{ GamePPAOffense }) = collect(keys(_property_map_GamePPAOffense))
Swagger.property_type(::Type{ GamePPAOffense }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GamePPAOffense[name]))}
Swagger.field_name(::Type{ GamePPAOffense }, property_name::Symbol) =  _property_map_GamePPAOffense[property_name]

function check_required(o::GamePPAOffense)
    true
end

function validate_property(::Type{ GamePPAOffense }, name::Symbol, val)
end
