# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct BoxScorePlayersUsage <: SwaggerModel
    player::Any # spec type: Union{ Nothing, String } # spec name: player
    team::Any # spec type: Union{ Nothing, String } # spec name: team
    position::Any # spec type: Union{ Nothing, String } # spec name: position
    total::Any # spec type: Union{ Nothing, Float32 } # spec name: total
    quarter1::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter1
    quarter2::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter2
    quarter3::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter3
    quarter4::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter4
    rushing::Any # spec type: Union{ Nothing, Float32 } # spec name: rushing
    passing::Any # spec type: Union{ Nothing, Float32 } # spec name: passing

    function BoxScorePlayersUsage(;player=nothing, team=nothing, position=nothing, total=nothing, quarter1=nothing, quarter2=nothing, quarter3=nothing, quarter4=nothing, rushing=nothing, passing=nothing)
        o = new()
        validate_property(BoxScorePlayersUsage, Symbol("player"), player)
        setfield!(o, Symbol("player"), player)
        validate_property(BoxScorePlayersUsage, Symbol("team"), team)
        setfield!(o, Symbol("team"), team)
        validate_property(BoxScorePlayersUsage, Symbol("position"), position)
        setfield!(o, Symbol("position"), position)
        validate_property(BoxScorePlayersUsage, Symbol("total"), total)
        setfield!(o, Symbol("total"), total)
        validate_property(BoxScorePlayersUsage, Symbol("quarter1"), quarter1)
        setfield!(o, Symbol("quarter1"), quarter1)
        validate_property(BoxScorePlayersUsage, Symbol("quarter2"), quarter2)
        setfield!(o, Symbol("quarter2"), quarter2)
        validate_property(BoxScorePlayersUsage, Symbol("quarter3"), quarter3)
        setfield!(o, Symbol("quarter3"), quarter3)
        validate_property(BoxScorePlayersUsage, Symbol("quarter4"), quarter4)
        setfield!(o, Symbol("quarter4"), quarter4)
        validate_property(BoxScorePlayersUsage, Symbol("rushing"), rushing)
        setfield!(o, Symbol("rushing"), rushing)
        validate_property(BoxScorePlayersUsage, Symbol("passing"), passing)
        setfield!(o, Symbol("passing"), passing)
        o
    end
end # type BoxScorePlayersUsage

const _property_map_BoxScorePlayersUsage = Dict{Symbol,Symbol}(Symbol("player")=>Symbol("player"), Symbol("team")=>Symbol("team"), Symbol("position")=>Symbol("position"), Symbol("total")=>Symbol("total"), Symbol("quarter1")=>Symbol("quarter1"), Symbol("quarter2")=>Symbol("quarter2"), Symbol("quarter3")=>Symbol("quarter3"), Symbol("quarter4")=>Symbol("quarter4"), Symbol("rushing")=>Symbol("rushing"), Symbol("passing")=>Symbol("passing"))
const _property_types_BoxScorePlayersUsage = Dict{Symbol,String}(Symbol("player")=>"String", Symbol("team")=>"String", Symbol("position")=>"String", Symbol("total")=>"Float32", Symbol("quarter1")=>"Float32", Symbol("quarter2")=>"Float32", Symbol("quarter3")=>"Float32", Symbol("quarter4")=>"Float32", Symbol("rushing")=>"Float32", Symbol("passing")=>"Float32")
Base.propertynames(::Type{ BoxScorePlayersUsage }) = collect(keys(_property_map_BoxScorePlayersUsage))
Swagger.property_type(::Type{ BoxScorePlayersUsage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BoxScorePlayersUsage[name]))}
Swagger.field_name(::Type{ BoxScorePlayersUsage }, property_name::Symbol) =  _property_map_BoxScorePlayersUsage[property_name]

function check_required(o::BoxScorePlayersUsage)
    true
end

function validate_property(::Type{ BoxScorePlayersUsage }, name::Symbol, val)
end
