# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AdvancedGameStat <: SwaggerModel
    gameId::Any # spec type: Union{ Nothing, Int32 } # spec name: gameId
    season::Any # spec type: Union{ Nothing, Int32 } # spec name: season
    week::Any # spec type: Union{ Nothing, Int32 } # spec name: week
    team::Any # spec type: Union{ Nothing, String } # spec name: team
    opponent::Any # spec type: Union{ Nothing, String } # spec name: opponent
    offense::Any # spec type: Union{ Nothing, AdvancedGameStatOffense } # spec name: offense
    defense::Any # spec type: Union{ Nothing, AdvancedGameStatOffense } # spec name: defense

    function AdvancedGameStat(;gameId=nothing, season=nothing, week=nothing, team=nothing, opponent=nothing, offense=nothing, defense=nothing)
        o = new()
        validate_property(AdvancedGameStat, Symbol("gameId"), gameId)
        setfield!(o, Symbol("gameId"), gameId)
        validate_property(AdvancedGameStat, Symbol("season"), season)
        setfield!(o, Symbol("season"), season)
        validate_property(AdvancedGameStat, Symbol("week"), week)
        setfield!(o, Symbol("week"), week)
        validate_property(AdvancedGameStat, Symbol("team"), team)
        setfield!(o, Symbol("team"), team)
        validate_property(AdvancedGameStat, Symbol("opponent"), opponent)
        setfield!(o, Symbol("opponent"), opponent)
        validate_property(AdvancedGameStat, Symbol("offense"), offense)
        setfield!(o, Symbol("offense"), offense)
        validate_property(AdvancedGameStat, Symbol("defense"), defense)
        setfield!(o, Symbol("defense"), defense)
        o
    end
end # type AdvancedGameStat

const _property_map_AdvancedGameStat = Dict{Symbol,Symbol}(Symbol("gameId")=>Symbol("gameId"), Symbol("season")=>Symbol("season"), Symbol("week")=>Symbol("week"), Symbol("team")=>Symbol("team"), Symbol("opponent")=>Symbol("opponent"), Symbol("offense")=>Symbol("offense"), Symbol("defense")=>Symbol("defense"))
const _property_types_AdvancedGameStat = Dict{Symbol,String}(Symbol("gameId")=>"Int32", Symbol("season")=>"Int32", Symbol("week")=>"Int32", Symbol("team")=>"String", Symbol("opponent")=>"String", Symbol("offense")=>"AdvancedGameStatOffense", Symbol("defense")=>"AdvancedGameStatOffense")
Base.propertynames(::Type{ AdvancedGameStat }) = collect(keys(_property_map_AdvancedGameStat))
Swagger.property_type(::Type{ AdvancedGameStat }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdvancedGameStat[name]))}
Swagger.field_name(::Type{ AdvancedGameStat }, property_name::Symbol) =  _property_map_AdvancedGameStat[property_name]

function check_required(o::AdvancedGameStat)
    true
end

function validate_property(::Type{ AdvancedGameStat }, name::Symbol, val)
end
