# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct PlayerSeasonPPAAveragePPA <: SwaggerModel
    all::Any # spec type: Union{ Nothing, Float32 } # spec name: all
    pass::Any # spec type: Union{ Nothing, Float32 } # spec name: pass
    rush::Any # spec type: Union{ Nothing, Float32 } # spec name: rush
    firstDown::Any # spec type: Union{ Nothing, Float32 } # spec name: firstDown
    secondDown::Any # spec type: Union{ Nothing, Float32 } # spec name: secondDown
    thirdDown::Any # spec type: Union{ Nothing, Float32 } # spec name: thirdDown
    standardDowns::Any # spec type: Union{ Nothing, Float32 } # spec name: standardDowns
    passingDowns::Any # spec type: Union{ Nothing, Float32 } # spec name: passingDowns

    function PlayerSeasonPPAAveragePPA(;all=nothing, pass=nothing, rush=nothing, firstDown=nothing, secondDown=nothing, thirdDown=nothing, standardDowns=nothing, passingDowns=nothing)
        o = new()
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("all"), all)
        setfield!(o, Symbol("all"), all)
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("pass"), pass)
        setfield!(o, Symbol("pass"), pass)
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("rush"), rush)
        setfield!(o, Symbol("rush"), rush)
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("firstDown"), firstDown)
        setfield!(o, Symbol("firstDown"), firstDown)
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("secondDown"), secondDown)
        setfield!(o, Symbol("secondDown"), secondDown)
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("thirdDown"), thirdDown)
        setfield!(o, Symbol("thirdDown"), thirdDown)
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("standardDowns"), standardDowns)
        setfield!(o, Symbol("standardDowns"), standardDowns)
        validate_property(PlayerSeasonPPAAveragePPA, Symbol("passingDowns"), passingDowns)
        setfield!(o, Symbol("passingDowns"), passingDowns)
        o
    end
end # type PlayerSeasonPPAAveragePPA

const _property_map_PlayerSeasonPPAAveragePPA = Dict{Symbol,Symbol}(Symbol("all")=>Symbol("all"), Symbol("pass")=>Symbol("pass"), Symbol("rush")=>Symbol("rush"), Symbol("firstDown")=>Symbol("firstDown"), Symbol("secondDown")=>Symbol("secondDown"), Symbol("thirdDown")=>Symbol("thirdDown"), Symbol("standardDowns")=>Symbol("standardDowns"), Symbol("passingDowns")=>Symbol("passingDowns"))
const _property_types_PlayerSeasonPPAAveragePPA = Dict{Symbol,String}(Symbol("all")=>"Float32", Symbol("pass")=>"Float32", Symbol("rush")=>"Float32", Symbol("firstDown")=>"Float32", Symbol("secondDown")=>"Float32", Symbol("thirdDown")=>"Float32", Symbol("standardDowns")=>"Float32", Symbol("passingDowns")=>"Float32")
Base.propertynames(::Type{ PlayerSeasonPPAAveragePPA }) = collect(keys(_property_map_PlayerSeasonPPAAveragePPA))
Swagger.property_type(::Type{ PlayerSeasonPPAAveragePPA }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlayerSeasonPPAAveragePPA[name]))}
Swagger.field_name(::Type{ PlayerSeasonPPAAveragePPA }, property_name::Symbol) =  _property_map_PlayerSeasonPPAAveragePPA[property_name]

function check_required(o::PlayerSeasonPPAAveragePPA)
    true
end

function validate_property(::Type{ PlayerSeasonPPAAveragePPA }, name::Symbol, val)
end
