# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct BoxScorePlayersPpa <: SwaggerModel
    player::Any # spec type: Union{ Nothing, String } # spec name: player
    team::Any # spec type: Union{ Nothing, String } # spec name: team
    position::Any # spec type: Union{ Nothing, String } # spec name: position
    average::Any # spec type: Union{ Nothing, BoxScorePlayersAverage } # spec name: average
    cumulative::Any # spec type: Union{ Nothing, BoxScorePlayersAverage } # spec name: cumulative

    function BoxScorePlayersPpa(;player=nothing, team=nothing, position=nothing, average=nothing, cumulative=nothing)
        o = new()
        validate_property(BoxScorePlayersPpa, Symbol("player"), player)
        setfield!(o, Symbol("player"), player)
        validate_property(BoxScorePlayersPpa, Symbol("team"), team)
        setfield!(o, Symbol("team"), team)
        validate_property(BoxScorePlayersPpa, Symbol("position"), position)
        setfield!(o, Symbol("position"), position)
        validate_property(BoxScorePlayersPpa, Symbol("average"), average)
        setfield!(o, Symbol("average"), average)
        validate_property(BoxScorePlayersPpa, Symbol("cumulative"), cumulative)
        setfield!(o, Symbol("cumulative"), cumulative)
        o
    end
end # type BoxScorePlayersPpa

const _property_map_BoxScorePlayersPpa = Dict{Symbol,Symbol}(Symbol("player")=>Symbol("player"), Symbol("team")=>Symbol("team"), Symbol("position")=>Symbol("position"), Symbol("average")=>Symbol("average"), Symbol("cumulative")=>Symbol("cumulative"))
const _property_types_BoxScorePlayersPpa = Dict{Symbol,String}(Symbol("player")=>"String", Symbol("team")=>"String", Symbol("position")=>"String", Symbol("average")=>"BoxScorePlayersAverage", Symbol("cumulative")=>"BoxScorePlayersAverage")
Base.propertynames(::Type{ BoxScorePlayersPpa }) = collect(keys(_property_map_BoxScorePlayersPpa))
Swagger.property_type(::Type{ BoxScorePlayersPpa }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BoxScorePlayersPpa[name]))}
Swagger.field_name(::Type{ BoxScorePlayersPpa }, property_name::Symbol) =  _property_map_BoxScorePlayersPpa[property_name]

function check_required(o::BoxScorePlayersPpa)
    true
end

function validate_property(::Type{ BoxScorePlayersPpa }, name::Symbol, val)
end
