# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AdvancedSeasonStat <: SwaggerModel
    season::Any # spec type: Union{ Nothing, Int32 } # spec name: season
    team::Any # spec type: Union{ Nothing, String } # spec name: team
    conference::Any # spec type: Union{ Nothing, String } # spec name: conference
    offense::Any # spec type: Union{ Nothing, AdvancedSeasonStatOffense } # spec name: offense
    defense::Any # spec type: Union{ Nothing, AdvancedSeasonStatDefense } # spec name: defense

    function AdvancedSeasonStat(;season=nothing, team=nothing, conference=nothing, offense=nothing, defense=nothing)
        o = new()
        validate_property(AdvancedSeasonStat, Symbol("season"), season)
        setfield!(o, Symbol("season"), season)
        validate_property(AdvancedSeasonStat, Symbol("team"), team)
        setfield!(o, Symbol("team"), team)
        validate_property(AdvancedSeasonStat, Symbol("conference"), conference)
        setfield!(o, Symbol("conference"), conference)
        validate_property(AdvancedSeasonStat, Symbol("offense"), offense)
        setfield!(o, Symbol("offense"), offense)
        validate_property(AdvancedSeasonStat, Symbol("defense"), defense)
        setfield!(o, Symbol("defense"), defense)
        o
    end
end # type AdvancedSeasonStat

const _property_map_AdvancedSeasonStat = Dict{Symbol,Symbol}(Symbol("season")=>Symbol("season"), Symbol("team")=>Symbol("team"), Symbol("conference")=>Symbol("conference"), Symbol("offense")=>Symbol("offense"), Symbol("defense")=>Symbol("defense"))
const _property_types_AdvancedSeasonStat = Dict{Symbol,String}(Symbol("season")=>"Int32", Symbol("team")=>"String", Symbol("conference")=>"String", Symbol("offense")=>"AdvancedSeasonStatOffense", Symbol("defense")=>"AdvancedSeasonStatDefense")
Base.propertynames(::Type{ AdvancedSeasonStat }) = collect(keys(_property_map_AdvancedSeasonStat))
Swagger.property_type(::Type{ AdvancedSeasonStat }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdvancedSeasonStat[name]))}
Swagger.field_name(::Type{ AdvancedSeasonStat }, property_name::Symbol) =  _property_map_AdvancedSeasonStat[property_name]

function check_required(o::AdvancedSeasonStat)
    true
end

function validate_property(::Type{ AdvancedSeasonStat }, name::Symbol, val)
end
