# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct PlayerGameTeams <: SwaggerModel
    school::Any # spec type: Union{ Nothing, PlayerGameSchool } # spec name: school
    homeAway::Any # spec type: Union{ Nothing, Bool } # spec name: homeAway
    points::Any # spec type: Union{ Nothing, Int32 } # spec name: points
    categories::Any # spec type: Union{ Nothing, Vector{PlayerGameCategories} } # spec name: categories

    function PlayerGameTeams(;school=nothing, homeAway=nothing, points=nothing, categories=nothing)
        o = new()
        validate_property(PlayerGameTeams, Symbol("school"), school)
        setfield!(o, Symbol("school"), school)
        validate_property(PlayerGameTeams, Symbol("homeAway"), homeAway)
        setfield!(o, Symbol("homeAway"), homeAway)
        validate_property(PlayerGameTeams, Symbol("points"), points)
        setfield!(o, Symbol("points"), points)
        validate_property(PlayerGameTeams, Symbol("categories"), categories)
        setfield!(o, Symbol("categories"), categories)
        o
    end
end # type PlayerGameTeams

const _property_map_PlayerGameTeams = Dict{Symbol,Symbol}(Symbol("school")=>Symbol("school"), Symbol("homeAway")=>Symbol("homeAway"), Symbol("points")=>Symbol("points"), Symbol("categories")=>Symbol("categories"))
const _property_types_PlayerGameTeams = Dict{Symbol,String}(Symbol("school")=>"PlayerGameSchool", Symbol("homeAway")=>"Bool", Symbol("points")=>"Int32", Symbol("categories")=>"Vector{PlayerGameCategories}")
Base.propertynames(::Type{ PlayerGameTeams }) = collect(keys(_property_map_PlayerGameTeams))
Swagger.property_type(::Type{ PlayerGameTeams }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlayerGameTeams[name]))}
Swagger.field_name(::Type{ PlayerGameTeams }, property_name::Symbol) =  _property_map_PlayerGameTeams[property_name]

function check_required(o::PlayerGameTeams)
    true
end

function validate_property(::Type{ PlayerGameTeams }, name::Symbol, val)
end
