# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AdvancedGameStatOffenseStandardDowns <: SwaggerModel
    ppa::Any # spec type: Union{ Nothing, Float32 } # spec name: ppa
    successRate::Any # spec type: Union{ Nothing, Float32 } # spec name: successRate
    explosiveness::Any # spec type: Union{ Nothing, Float32 } # spec name: explosiveness

    function AdvancedGameStatOffenseStandardDowns(;ppa=nothing, successRate=nothing, explosiveness=nothing)
        o = new()
        validate_property(AdvancedGameStatOffenseStandardDowns, Symbol("ppa"), ppa)
        setfield!(o, Symbol("ppa"), ppa)
        validate_property(AdvancedGameStatOffenseStandardDowns, Symbol("successRate"), successRate)
        setfield!(o, Symbol("successRate"), successRate)
        validate_property(AdvancedGameStatOffenseStandardDowns, Symbol("explosiveness"), explosiveness)
        setfield!(o, Symbol("explosiveness"), explosiveness)
        o
    end
end # type AdvancedGameStatOffenseStandardDowns

const _property_map_AdvancedGameStatOffenseStandardDowns = Dict{Symbol,Symbol}(Symbol("ppa")=>Symbol("ppa"), Symbol("successRate")=>Symbol("successRate"), Symbol("explosiveness")=>Symbol("explosiveness"))
const _property_types_AdvancedGameStatOffenseStandardDowns = Dict{Symbol,String}(Symbol("ppa")=>"Float32", Symbol("successRate")=>"Float32", Symbol("explosiveness")=>"Float32")
Base.propertynames(::Type{ AdvancedGameStatOffenseStandardDowns }) = collect(keys(_property_map_AdvancedGameStatOffenseStandardDowns))
Swagger.property_type(::Type{ AdvancedGameStatOffenseStandardDowns }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdvancedGameStatOffenseStandardDowns[name]))}
Swagger.field_name(::Type{ AdvancedGameStatOffenseStandardDowns }, property_name::Symbol) =  _property_map_AdvancedGameStatOffenseStandardDowns[property_name]

function check_required(o::AdvancedGameStatOffenseStandardDowns)
    true
end

function validate_property(::Type{ AdvancedGameStatOffenseStandardDowns }, name::Symbol, val)
end
