# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct TeamSPRatingSpecialTeams <: SwaggerModel
    rating::Any # spec type: Union{ Nothing, Float32 } # spec name: rating

    function TeamSPRatingSpecialTeams(;rating=nothing)
        o = new()
        validate_property(TeamSPRatingSpecialTeams, Symbol("rating"), rating)
        setfield!(o, Symbol("rating"), rating)
        o
    end
end # type TeamSPRatingSpecialTeams

const _property_map_TeamSPRatingSpecialTeams = Dict{Symbol,Symbol}(Symbol("rating")=>Symbol("rating"))
const _property_types_TeamSPRatingSpecialTeams = Dict{Symbol,String}(Symbol("rating")=>"Float32")
Base.propertynames(::Type{ TeamSPRatingSpecialTeams }) = collect(keys(_property_map_TeamSPRatingSpecialTeams))
Swagger.property_type(::Type{ TeamSPRatingSpecialTeams }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TeamSPRatingSpecialTeams[name]))}
Swagger.field_name(::Type{ TeamSPRatingSpecialTeams }, property_name::Symbol) =  _property_map_TeamSPRatingSpecialTeams[property_name]

function check_required(o::TeamSPRatingSpecialTeams)
    true
end

function validate_property(::Type{ TeamSPRatingSpecialTeams }, name::Symbol, val)
end
