# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct PlayerGameAthletes <: SwaggerModel
    id::Any # spec type: Union{ Nothing, Int32 } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    stat::Any # spec type: Union{ Nothing, String } # spec name: stat

    function PlayerGameAthletes(;id=nothing, name=nothing, stat=nothing)
        o = new()
        validate_property(PlayerGameAthletes, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(PlayerGameAthletes, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(PlayerGameAthletes, Symbol("stat"), stat)
        setfield!(o, Symbol("stat"), stat)
        o
    end
end # type PlayerGameAthletes

const _property_map_PlayerGameAthletes = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), Symbol("stat")=>Symbol("stat"))
const _property_types_PlayerGameAthletes = Dict{Symbol,String}(Symbol("id")=>"Int32", Symbol("name")=>"String", Symbol("stat")=>"String")
Base.propertynames(::Type{ PlayerGameAthletes }) = collect(keys(_property_map_PlayerGameAthletes))
Swagger.property_type(::Type{ PlayerGameAthletes }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlayerGameAthletes[name]))}
Swagger.field_name(::Type{ PlayerGameAthletes }, property_name::Symbol) =  _property_map_PlayerGameAthletes[property_name]

function check_required(o::PlayerGameAthletes)
    true
end

function validate_property(::Type{ PlayerGameAthletes }, name::Symbol, val)
end
