# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct BoxScoreTeamsOverall <: SwaggerModel
    total::Any # spec type: Union{ Nothing, Float32 } # spec name: total
    quarter1::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter1
    quarter2::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter2
    quarter3::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter3
    quarter4::Any # spec type: Union{ Nothing, Float32 } # spec name: quarter4

    function BoxScoreTeamsOverall(;total=nothing, quarter1=nothing, quarter2=nothing, quarter3=nothing, quarter4=nothing)
        o = new()
        validate_property(BoxScoreTeamsOverall, Symbol("total"), total)
        setfield!(o, Symbol("total"), total)
        validate_property(BoxScoreTeamsOverall, Symbol("quarter1"), quarter1)
        setfield!(o, Symbol("quarter1"), quarter1)
        validate_property(BoxScoreTeamsOverall, Symbol("quarter2"), quarter2)
        setfield!(o, Symbol("quarter2"), quarter2)
        validate_property(BoxScoreTeamsOverall, Symbol("quarter3"), quarter3)
        setfield!(o, Symbol("quarter3"), quarter3)
        validate_property(BoxScoreTeamsOverall, Symbol("quarter4"), quarter4)
        setfield!(o, Symbol("quarter4"), quarter4)
        o
    end
end # type BoxScoreTeamsOverall

const _property_map_BoxScoreTeamsOverall = Dict{Symbol,Symbol}(Symbol("total")=>Symbol("total"), Symbol("quarter1")=>Symbol("quarter1"), Symbol("quarter2")=>Symbol("quarter2"), Symbol("quarter3")=>Symbol("quarter3"), Symbol("quarter4")=>Symbol("quarter4"))
const _property_types_BoxScoreTeamsOverall = Dict{Symbol,String}(Symbol("total")=>"Float32", Symbol("quarter1")=>"Float32", Symbol("quarter2")=>"Float32", Symbol("quarter3")=>"Float32", Symbol("quarter4")=>"Float32")
Base.propertynames(::Type{ BoxScoreTeamsOverall }) = collect(keys(_property_map_BoxScoreTeamsOverall))
Swagger.property_type(::Type{ BoxScoreTeamsOverall }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BoxScoreTeamsOverall[name]))}
Swagger.field_name(::Type{ BoxScoreTeamsOverall }, property_name::Symbol) =  _property_map_BoxScoreTeamsOverall[property_name]

function check_required(o::BoxScoreTeamsOverall)
    true
end

function validate_property(::Type{ BoxScoreTeamsOverall }, name::Symbol, val)
end
