# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AdvancedSeasonStatOffenseStandardDowns <: SwaggerModel
    rate::Any # spec type: Union{ Nothing, Float32 } # spec name: rate
    ppa::Any # spec type: Union{ Nothing, Float32 } # spec name: ppa
    successRate::Any # spec type: Union{ Nothing, Float32 } # spec name: successRate
    explosiveness::Any # spec type: Union{ Nothing, Float32 } # spec name: explosiveness

    function AdvancedSeasonStatOffenseStandardDowns(;rate=nothing, ppa=nothing, successRate=nothing, explosiveness=nothing)
        o = new()
        validate_property(AdvancedSeasonStatOffenseStandardDowns, Symbol("rate"), rate)
        setfield!(o, Symbol("rate"), rate)
        validate_property(AdvancedSeasonStatOffenseStandardDowns, Symbol("ppa"), ppa)
        setfield!(o, Symbol("ppa"), ppa)
        validate_property(AdvancedSeasonStatOffenseStandardDowns, Symbol("successRate"), successRate)
        setfield!(o, Symbol("successRate"), successRate)
        validate_property(AdvancedSeasonStatOffenseStandardDowns, Symbol("explosiveness"), explosiveness)
        setfield!(o, Symbol("explosiveness"), explosiveness)
        o
    end
end # type AdvancedSeasonStatOffenseStandardDowns

const _property_map_AdvancedSeasonStatOffenseStandardDowns = Dict{Symbol,Symbol}(Symbol("rate")=>Symbol("rate"), Symbol("ppa")=>Symbol("ppa"), Symbol("successRate")=>Symbol("successRate"), Symbol("explosiveness")=>Symbol("explosiveness"))
const _property_types_AdvancedSeasonStatOffenseStandardDowns = Dict{Symbol,String}(Symbol("rate")=>"Float32", Symbol("ppa")=>"Float32", Symbol("successRate")=>"Float32", Symbol("explosiveness")=>"Float32")
Base.propertynames(::Type{ AdvancedSeasonStatOffenseStandardDowns }) = collect(keys(_property_map_AdvancedSeasonStatOffenseStandardDowns))
Swagger.property_type(::Type{ AdvancedSeasonStatOffenseStandardDowns }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdvancedSeasonStatOffenseStandardDowns[name]))}
Swagger.field_name(::Type{ AdvancedSeasonStatOffenseStandardDowns }, property_name::Symbol) =  _property_map_AdvancedSeasonStatOffenseStandardDowns[property_name]

function check_required(o::AdvancedSeasonStatOffenseStandardDowns)
    true
end

function validate_property(::Type{ AdvancedSeasonStatOffenseStandardDowns }, name::Symbol, val)
end
