# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AdvancedSeasonStatOffenseRushingPlays <: SwaggerModel
    rate::Any # spec type: Union{ Nothing, Float32 } # spec name: rate
    ppa::Any # spec type: Union{ Nothing, Float32 } # spec name: ppa
    totalPPA::Any # spec type: Union{ Nothing, Float32 } # spec name: totalPPA
    successRate::Any # spec type: Union{ Nothing, Float32 } # spec name: successRate
    explosiveness::Any # spec type: Union{ Nothing, Float32 } # spec name: explosiveness

    function AdvancedSeasonStatOffenseRushingPlays(;rate=nothing, ppa=nothing, totalPPA=nothing, successRate=nothing, explosiveness=nothing)
        o = new()
        validate_property(AdvancedSeasonStatOffenseRushingPlays, Symbol("rate"), rate)
        setfield!(o, Symbol("rate"), rate)
        validate_property(AdvancedSeasonStatOffenseRushingPlays, Symbol("ppa"), ppa)
        setfield!(o, Symbol("ppa"), ppa)
        validate_property(AdvancedSeasonStatOffenseRushingPlays, Symbol("totalPPA"), totalPPA)
        setfield!(o, Symbol("totalPPA"), totalPPA)
        validate_property(AdvancedSeasonStatOffenseRushingPlays, Symbol("successRate"), successRate)
        setfield!(o, Symbol("successRate"), successRate)
        validate_property(AdvancedSeasonStatOffenseRushingPlays, Symbol("explosiveness"), explosiveness)
        setfield!(o, Symbol("explosiveness"), explosiveness)
        o
    end
end # type AdvancedSeasonStatOffenseRushingPlays

const _property_map_AdvancedSeasonStatOffenseRushingPlays = Dict{Symbol,Symbol}(Symbol("rate")=>Symbol("rate"), Symbol("ppa")=>Symbol("ppa"), Symbol("totalPPA")=>Symbol("totalPPA"), Symbol("successRate")=>Symbol("successRate"), Symbol("explosiveness")=>Symbol("explosiveness"))
const _property_types_AdvancedSeasonStatOffenseRushingPlays = Dict{Symbol,String}(Symbol("rate")=>"Float32", Symbol("ppa")=>"Float32", Symbol("totalPPA")=>"Float32", Symbol("successRate")=>"Float32", Symbol("explosiveness")=>"Float32")
Base.propertynames(::Type{ AdvancedSeasonStatOffenseRushingPlays }) = collect(keys(_property_map_AdvancedSeasonStatOffenseRushingPlays))
Swagger.property_type(::Type{ AdvancedSeasonStatOffenseRushingPlays }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdvancedSeasonStatOffenseRushingPlays[name]))}
Swagger.field_name(::Type{ AdvancedSeasonStatOffenseRushingPlays }, property_name::Symbol) =  _property_map_AdvancedSeasonStatOffenseRushingPlays[property_name]

function check_required(o::AdvancedSeasonStatOffenseRushingPlays)
    true
end

function validate_property(::Type{ AdvancedSeasonStatOffenseRushingPlays }, name::Symbol, val)
end
