# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct PlayerGame <: SwaggerModel
    id::Any # spec type: Union{ Nothing, Int32 } # spec name: id
    teams::Any # spec type: Union{ Nothing, Vector{PlayerGameTeams} } # spec name: teams

    function PlayerGame(;id=nothing, teams=nothing)
        o = new()
        validate_property(PlayerGame, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(PlayerGame, Symbol("teams"), teams)
        setfield!(o, Symbol("teams"), teams)
        o
    end
end # type PlayerGame

const _property_map_PlayerGame = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("teams")=>Symbol("teams"))
const _property_types_PlayerGame = Dict{Symbol,String}(Symbol("id")=>"Int32", Symbol("teams")=>"Vector{PlayerGameTeams}")
Base.propertynames(::Type{ PlayerGame }) = collect(keys(_property_map_PlayerGame))
Swagger.property_type(::Type{ PlayerGame }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlayerGame[name]))}
Swagger.field_name(::Type{ PlayerGame }, property_name::Symbol) =  _property_map_PlayerGame[property_name]

function check_required(o::PlayerGame)
    true
end

function validate_property(::Type{ PlayerGame }, name::Symbol, val)
end
