# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AdvancedGameStatOffenseRushingPlays <: SwaggerModel
    ppa::Any # spec type: Union{ Nothing, Float32 } # spec name: ppa
    totalPPA::Any # spec type: Union{ Nothing, Float32 } # spec name: totalPPA
    successRate::Any # spec type: Union{ Nothing, Float32 } # spec name: successRate
    explosiveness::Any # spec type: Union{ Nothing, Float32 } # spec name: explosiveness

    function AdvancedGameStatOffenseRushingPlays(;ppa=nothing, totalPPA=nothing, successRate=nothing, explosiveness=nothing)
        o = new()
        validate_property(AdvancedGameStatOffenseRushingPlays, Symbol("ppa"), ppa)
        setfield!(o, Symbol("ppa"), ppa)
        validate_property(AdvancedGameStatOffenseRushingPlays, Symbol("totalPPA"), totalPPA)
        setfield!(o, Symbol("totalPPA"), totalPPA)
        validate_property(AdvancedGameStatOffenseRushingPlays, Symbol("successRate"), successRate)
        setfield!(o, Symbol("successRate"), successRate)
        validate_property(AdvancedGameStatOffenseRushingPlays, Symbol("explosiveness"), explosiveness)
        setfield!(o, Symbol("explosiveness"), explosiveness)
        o
    end
end # type AdvancedGameStatOffenseRushingPlays

const _property_map_AdvancedGameStatOffenseRushingPlays = Dict{Symbol,Symbol}(Symbol("ppa")=>Symbol("ppa"), Symbol("totalPPA")=>Symbol("totalPPA"), Symbol("successRate")=>Symbol("successRate"), Symbol("explosiveness")=>Symbol("explosiveness"))
const _property_types_AdvancedGameStatOffenseRushingPlays = Dict{Symbol,String}(Symbol("ppa")=>"Float32", Symbol("totalPPA")=>"Float32", Symbol("successRate")=>"Float32", Symbol("explosiveness")=>"Float32")
Base.propertynames(::Type{ AdvancedGameStatOffenseRushingPlays }) = collect(keys(_property_map_AdvancedGameStatOffenseRushingPlays))
Swagger.property_type(::Type{ AdvancedGameStatOffenseRushingPlays }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdvancedGameStatOffenseRushingPlays[name]))}
Swagger.field_name(::Type{ AdvancedGameStatOffenseRushingPlays }, property_name::Symbol) =  _property_map_AdvancedGameStatOffenseRushingPlays[property_name]

function check_required(o::AdvancedGameStatOffenseRushingPlays)
    true
end

function validate_property(::Type{ AdvancedGameStatOffenseRushingPlays }, name::Symbol, val)
end
